"UI/Resource/messagedialog.res"
{
	"MessageDialog"
	{
		"ControlName"			"CMessageDialog"
		"fieldName"				"MessageDialog"
		"xpos"					"c-150"
		"ypos"					"140"
		"wide"					"300"
		"tall"					"230"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
	}

	"AnimatingImagePanel"
	{
		"ControlName"		"AnimatingPanel"
		"fieldName"			"AnimatingImagePanel"
		"xpos"				"15"
		"ypos"				"15"
		"zpos"				"0"
		"wide"				"50"
		"tall"				"50"
		"autoResize"		"1"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
	}

	"TitleLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TitleLabel"
		"font"				"FontMedium"
		"textAlignment"		"north"
		"xpos"				"0"
		"ypos"				"15"
		"zpos"				"1"
		"wide"				"300"
		"tall"				"30"
		"autoResize"		"1"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
	}

	"MessageLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"MessageLabel"
		"font"				"FontSmall"
		"textAlignment"		"north"
		"xpos"				"10"
		"ypos"				"50"
		"zpos"				"1"
		"wide"				"280"
		"tall"				"170"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"centerwrap"		"1"
	}

	"ConfirmButton"
	{
		"ControlName"				"Button"
		"fieldName"					"ConfirmButton"
		"xpos"						"62"
		"ypos"						"190"
		"zpos"						"20"
		"wide"						"175"
		"tall"						"25"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"labelText"					"#GameUI_OK"
		"font"						"FontSmall"
		"textAlignment"				"center"
		"textinsetx"				"50"
		"dulltext"					"0"
		"brighttext"				"0"
		"Command"					"Close"
	}
}
