"ui/workshop/infobox.res"
{
	"CreateWorkshopInfoBox"
	{
		"ControlName"					"CCreateWorkshopInfoBox"
		"fieldName"						"CreateWorkshopInfoBox"
		"xpos"							"4"
		"ypos"							"4"
		"wide"							"250"
		"tall"							"40"
		"RoundedCorners"				"15"
		"visible"						"1"
		"enabled"						"1"
		"settitlebarvisible"			"0"
	}
	"Text"
	{
		"ControlName"				"Label"
		"fieldName"					"Text"
		"xpos"						"32"
		"ypos"						"5"
		"wide"						"384"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"My Text Goes Here..."
		"textAlignment"				"west"
		"font"						"Title"
	}
	"State"
	{
		"ControlName"				"Label"
		"fieldName"					"State"
		"xpos"						"35"
		"ypos"						"24"
		"wide"						"384"
		"tall"						"15"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"12345"
		"textAlignment"				"west"
		"font"						"AchievementItemDescription"
	}
	"Progress"
	{
		"ControlName"				"ProgressBar"
		"fieldName"					"Progress"
		"xpos"						"15"
		"ypos"						"40"
		"wide"						"225"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
	}
	"Icon"
	{
		"ControlName"				"ImagePanel"
		"fieldName"					"Icon"
		"xpos"						"10"
		"ypos"						"10"
		"wide"						"24"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"image"						"resource/icon_steam"
	}
}
