"ui/resource/workshop/mainlist.res"
{
	"WorkshopSubList"
	{
		"ControlName"		"CWorkshopSubList"
		"fieldName"		"WorkshopSubList"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"526"
		"tall"		"260"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"listpanel"
	{
		"ControlName"		"WorkshopItemList"
		"fieldName"		"listpanel"
		"xpos"		"1"
		"ypos"		"1"
		"wide"		"520"
		"tall"		"220"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"category"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"category"
		"xpos"		"84"
		"ypos"		"232"
		"wide"		"220"
		"tall"		"16"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"category_label"
	{
		"ControlName"		"Label"
		"fieldName"		"category_label"
		"xpos"		"9"
		"ypos"		"229"
		"wide"		"69"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_CategoryFilter"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"DefaultProportional"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"252"
		"ypos"		"55"
		"wide"		"133"
		"tall"		"177"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"Title"		"#Frame_Untitled"
	}
}
