"ui/workshop/uploaded.res"
{
	"WorkshopSubUploaded"
	{
		"ControlName"		"CWorkshopSubUploaded"
		"fieldName"		"WorkshopSubUploaded"
		"xpos"		"388"
		"ypos"		"239"
		"wide"		"630"
		"tall"		"444"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"listpanel"
	{
		"ControlName"	"WorkshopItemList"
		"fieldName"		"listpanel"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"2"
		"ypos"			"2"
		"wide"			"520"
		"tall"			"220"
	}
	"Refresh"
	{
		"ControlName"			"Button"
		"fieldName"				"Refresh"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"420"
		"ypos"					"225"
		"wide"					"80"
		"tall"					"15"
		"labelText"				"#Phoenix_Workshop_Refresh"
		"command"				"Refresh"
		"font"					"DefaultProportional"
		"textAlignment"			"center"
	}
}
