"ui/workshop/upload.res"
{
	"WorkshopSubUpload"
	{
		"ControlName"		"CWorkshopSubUpload"
		"fieldName"		"WorkshopSubUpload"
		"xpos"		"388"
		"ypos"		"239"
		"wide"		"530"
		"tall"		"344"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	// Addon Image
	"BrowseImageText"
	{
		"ControlName"				"Label"
		"fieldName"					"BrowseImageText"
		"xpos"						"10"
		"ypos"						"2"
		"wide"						"384"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_PreviewImage"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
	}
	"AddonImage"
	{
		"ControlName"			"ImagePanel"
		"fieldName"				"AddonImage"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"10"
		"ypos"					"20"
		"wide"					"120"
		"tall"					"60"
		"fillcolor"				"25 25 25"
	}
	"BrowseImage"
	{
		"ControlName"			"Button"
		"fieldName"				"BrowseImage"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"10"
		"ypos"					"80"
		"wide"					"120"
		"tall"					"18"
		"labelText"				"#Phoenix_Workshop_Upload_ChooseImage"
		"font"					"DefaultProportional"
		"command"				"BrowseImage"
	}
	// Content Folder
	"BrowseFolderText"
	{
		"ControlName"				"Label"
		"fieldName"					"BrowseFolderText"
		"xpos"						"10"
		"ypos"						"100"
		"wide"						"120"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_ContentFolder"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
	}
	"BrowseFolderTextBox"
	{
		"ControlName"			"TextEntry"
		"fieldName"				"BrowseFolderTextBox"
		"visible"				"1"
		"enabled"				"1"
		"editable"				"0"
		"xpos"					"10"
		"ypos"					"120"
		"wide"					"120"
		"font"					"DefaultSmallProportional"
		"tall"					"14"
	}
	"BrowseFolder"
	{
		"ControlName"			"Button"
		"fieldName"				"BrowseFolder"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"130"
		"ypos"					"120"
		"wide"					"14"
		"tall"					"14"
		"labelText"				"..."
		"font"					"DefaultProportional"
		"textAlignment"			"center"
		"command"				"BrowseFolder"
	}
	// Changelog
	"ChangeLogText"
	{
		"ControlName"				"Label"
		"fieldName"					"ChangeLogText"
		"xpos"						"10"
		"ypos"						"140"
		"wide"						"300"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_Changelog"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
	}
	"ChangeLogTextBox"
	{
		"ControlName"				"TextEntry"
		"fieldName"					"ChangeLogTextBox"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"10"
		"ypos"						"160"
		"wide"						"135"
		"tall"						"70"
		"font"						"DefaultProportional"
	}
	// Addon Title
	"AddonTitleText"
	{
		"ControlName"				"Label"
		"fieldName"					"AddonTitleText"
		"xpos"						"160"
		"ypos"						"2"
		"wide"						"300"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_Title"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
	}
	"AddonTitleTextBox"
	{
		"ControlName"				"TextEntry"
		"fieldName"					"AddonTitleTextBox"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"160"
		"ypos"						"20"
		"wide"						"190"
		"tall"						"20"
		"font"						"DefaultProportional"
	}
	// Addon Description
	"AddonDescText"
	{
		"ControlName"				"Label"
		"fieldName"					"AddonDescText"
		"xpos"						"160"
		"ypos"						"40"
		"wide"						"190"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_Desc"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
	}
	"AddonDescTextBox"
	{
		"ControlName"			"TextEntry"
		"fieldName"				"AddonDescTextBox"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"160"
		"ypos"					"60"
		"wide"					"190"
		"tall"					"100"
		"font"					"DefaultProportional"
	}
	// The tags
	"TagsText"
	{
		"ControlName"				"Label"
		"fieldName"					"TagsText"
		"xpos"						"360"
		"ypos"						"10"
		"wide"						"215"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_Tags"
		"font"						"DefaultProportional"
		"textAlignment"				"west"
		"fillcolor"					"25 25 25"
	}
	"Tags"
	{
		"ControlName"				"Panel"
		"fieldName"					"Tags"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"360"
		"ypos"						"30"
		"wide"						"150"
		"tall"						"165"
		"font"						"DefaultProportional"
	}
	// Visibility
	"VisibilityText"
	{
		"ControlName"				"Label"
		"fieldName"					"VisibilityText"
		"xpos"						"160"
		"ypos"						"160"
		"wide"						"40"
		"tall"						"24"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_Upload_Visibility"
		"textAlignment"				"west"
		"font"						"DefaultProportional"
	}
	"Visibility"
	{
		"ControlName"				"ComboBox"
		"fieldName"					"Visibility"
		"font"						"DefaultProportional"
		"visible"					"1"
		"enabled"					"1"
		"xpos"						"200"
		"ypos"						"164"
		"wide"						"115"
		"tall"						"18"
	}
	// Upload Button
	"AddonUpload"
	{
		"ControlName"			"Button"
		"fieldName"				"AddonUpload"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"360"
		"ypos"					"200"
		"wide"					"150"
		"tall"					"18"
		"textAlignment"			"center"
		"labelText"				"#Phoenix_Workshop_Upload_Addon"
		"font"					"DefaultProportional"
		"command"				"AddonUpload"
	}
	// Reset Button
	"AddonReset"
	{
		"ControlName"			"Button"
		"fieldName"				"AddonReset"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"360"
		"ypos"					"220"
		"wide"					"150"
		"tall"					"18"
		"textAlignment"			"center"
		"labelText"				"#Phoenix_Workshop_Upload_Reset"
		"font"					"DefaultProportional"
		"command"				"Reset"
	}
	// Progressbar
	"ProgressBarText"
	{
		"ControlName"				"Label"
		"fieldName"					"ProgressBarText"
		"xpos"						"160"
		"ypos"						"210"
		"wide"						"190"
		"tall"						"20"
		"autoResize"				"0"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					"#Phoenix_Workshop_UpdateStatus_PreparingConfig"
		"font"						"DefaultProportional"
		"textAlignment"				"center"
	}
	"ProgressBar"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"ProgressBar"
		"visible"				"1"
		"enabled"				"1"
		"progress"				"0.5"
		"xpos"					"160"
		"ypos"					"230"
		"wide"					"190"
		"tall"					"10"
		"textAlignment"			"center"
	}
}
