"ui/resource/workshop/upload.res"
{
	"WorkshopSubUpload"
	{
		"ControlName"		"CWorkshopSubUpload"
		"fieldName"		"WorkshopSubUpload"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"792"
		"tall"		"508"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"AddonDescTextBox"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"AddonDescTextBox"
		"xpos"		"260"
		"ypos"		"90"
		"wide"		"300"
		"tall"		"185"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AddonTitleTextBox"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"AddonTitleTextBox"
		"xpos"		"260"
		"ypos"		"40"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"BrowseFolderTextBox"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"BrowseFolderTextBox"
		"xpos"		"15"
		"ypos"		"400"
		"wide"		"235"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AddonImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"AddonImage"
		"xpos"		"15"
		"ypos"		"40"
		"wide"		"235"
		"tall"		"235"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"fillcolor"		"25 25 25"
		"scaleImage"		"1"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
	"Visibility"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Visibility"
		"xpos"		"570"
		"ypos"		"400"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Tags1"
	{
		"ControlName"		"CheckButtonList"
		"fieldName"		"Tags1"
		"xpos"		"570"
		"ypos"		"40"
		"wide"		"215"
		"tall"		"165"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Tags2"
	{
		"ControlName"		"CheckButtonList"
		"fieldName"		"Tags2"
		"xpos"		"570"
		"ypos"		"224"
		"wide"		"215"
		"tall"		"145"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ChangeLogText"
	{
		"ControlName"		"Label"
		"fieldName"		"ChangeLogText"
		"xpos"		"15"
		"ypos"		"365"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Changelog"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"ChangeLogTextBox"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ChangeLogTextBox"
		"xpos"		"15"
		"ypos"		"390"
		"wide"		"300"
		"tall"		"100"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AddonUpload"
	{
		"ControlName"		"Button"
		"fieldName"		"AddonUpload"
		"xpos"		"570"
		"ypos"		"435"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Addon"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Command"		"AddonUpload"
		"Default"		"0"
	}
	"AddonReset"
	{
		"ControlName"		"Button"
		"fieldName"		"AddonReset"
		"xpos"		"570"
		"ypos"		"470"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Reset"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Command"		"Reset"
		"Default"		"0"
	}
	"ProgressBar"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"ProgressBar"
		"xpos"		"15"
		"ypos"		"444"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"Progress"		"0.500000"
	}
	"ProgressBarText"
	{
		"ControlName"		"Label"
		"fieldName"		"ProgressBarText"
		"xpos"		"15"
		"ypos"		"420"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_UpdateStatus_PreparingConfig"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"BrowseImageText"
	{
		"ControlName"		"Label"
		"fieldName"		"BrowseImageText"
		"xpos"		"15"
		"ypos"		"15"
		"wide"		"384"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_PreviewImage"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"BrowseImage"
	{
		"ControlName"		"Button"
		"fieldName"		"BrowseImage"
		"xpos"		"15"
		"ypos"		"284"
		"wide"		"235"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_ChooseImage"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Command"		"BrowseImage"
		"Default"		"0"
	}
	"BrowseFolderText"
	{
		"ControlName"		"Label"
		"fieldName"		"BrowseFolderText"
		"xpos"		"14"
		"ypos"		"370"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_ContentFolder"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"BrowseFolder"
	{
		"ControlName"		"Button"
		"fieldName"		"BrowseFolder"
		"xpos"		"254"
		"ypos"		"400"
		"wide"		"24"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"..."
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
		"Command"		"BrowseFolder"
		"Default"		"1"
	}
	"AddonTitleText"
	{
		"ControlName"		"Label"
		"fieldName"		"AddonTitleText"
		"xpos"		"260"
		"ypos"		"15"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"AddonDescText"
	{
		"ControlName"		"Label"
		"fieldName"		"AddonDescText"
		"xpos"		"260"
		"ypos"		"65"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Desc"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Tags1Text"
	{
		"ControlName"		"Label"
		"fieldName"		"Tags1Text"
		"xpos"		"570"
		"ypos"		"15"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Tags1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Tags2Text"
	{
		"ControlName"		"Label"
		"fieldName"		"Tags2Text"
		"xpos"		"570"
		"ypos"		"200"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Tags2"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"Tags3"
	{
		"ControlName"		"Panel"
		"fieldName"		"Tags3"
		"xpos"		"350"
		"ypos"		"340"
		"wide"		"215"
		"tall"		"145"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"VisibilityText"
	{
		"ControlName"		"Label"
		"fieldName"		"VisibilityText"
		"xpos"		"570"
		"ypos"		"375"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_Upload_Visibility"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"443"
		"tall"		"460"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"Title"		"#Frame_Untitled"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"260"
		"ypos"		"15"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"PinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Phoenix_Workshop_TitleEntry"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"autowidetocontents"		"0"
		"useproportionalinsets"		"0"
	}
}
